import { Product } from '@/types/database';

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'demo-prod-01',
    seller_id: 'demo-seller-walboy',
    title: 'iPhone 15 Pro Max 256GB - Titane Naturel',
    description: 'iPhone 15 Pro Max état neuf sous boîte scellée. Facture d\'origine et garantie Apple internationale. Livré avec chargeur rapide et coque de protection MagSafe.',
    price_pi: 85.5,
    image_url: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1591337676887-a217a6970a8a?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&auto=format&fit=crop&q=80',
    ],
    category: 'Téléphones',
    status: 'active',
    stock: 3,
    views_count: 342,
    is_demo: true,
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      username: 'PiTechOfficial',
      is_seller: true,
    },
  },
  {
    id: 'demo-prod-02',
    seller_id: 'demo-seller-nordic',
    title: 'MacBook Pro 16" M3 Max 36GB / 1TB SSD',
    description: 'Station de travail ultra-performante pour développeurs et créateurs. Écran Liquid Retina XDR exceptionnel. 100% santé batterie.',
    price_pi: 195.0,
    image_url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&auto=format&fit=crop&q=80',
    ],
    category: 'Ordinateurs',
    status: 'active',
    stock: 2,
    views_count: 512,
    is_demo: true,
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      username: 'SiliconPioneer',
      is_seller: true,
    },
  },
  {
    id: 'demo-prod-03',
    seller_id: 'demo-seller-audio',
    title: 'Casque Audio Sony WH-1000XM5 Réduction de Bruit',
    description: 'Casque sans fil haut de gamme avec réduction active du bruit de pointe. Autonomie 30h, son spatialisé Hi-Res et confort optimal pour les longs trajets.',
    price_pi: 24.0,
    image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&auto=format&fit=crop&q=80',
    ],
    category: 'Électronique',
    status: 'active',
    stock: 8,
    views_count: 220,
    is_demo: true,
    created_at: new Date(Date.now() - 3600000 * 20).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      username: 'AudioVibes',
      is_seller: true,
    },
  },
  {
    id: 'demo-prod-04',
    seller_id: 'demo-seller-kicks',
    title: 'Sneakers Nike Air Jordan 1 Retro High OG - Édition Limitée',
    description: 'Paire authentique certifiée neuve en boîte avec étiquettes. Taille EU 43 / US 9.5. Cuir premium et colorway emblématique.',
    price_pi: 18.5,
    image_url: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop&q=80',
    ],
    category: 'Chaussures',
    status: 'active',
    stock: 4,
    views_count: 189,
    is_demo: true,
    created_at: new Date(Date.now() - 3600000 * 30).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      username: 'SneakerHead_Pi',
      is_seller: true,
    },
  },
  {
    id: 'demo-prod-05',
    seller_id: 'demo-seller-fashion',
    title: 'Veste Coupe-Vent Technique Minimaliste Urban Style',
    description: 'Matière imperméable respirante et coutures étanches. Coupe moderne et épurée parfaite pour la mi-saison et les sorties urbaines.',
    price_pi: 7.2,
    image_url: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1544441893-675973e31985?w=800&auto=format&fit=crop&q=80',
    ],
    category: 'Mode',
    status: 'active',
    stock: 12,
    views_count: 140,
    is_demo: true,
    created_at: new Date(Date.now() - 3600000 * 48).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      username: 'UrbanThreads',
      is_seller: true,
    },
  },
  {
    id: 'demo-prod-06',
    seller_id: 'demo-seller-console',
    title: 'Console PlayStation 5 Slim Edition + 2 Manettes DualSense',
    description: 'Console neuve en boîte avec 2 manettes sans fil et câbles HDMI 2.1 Ultra-High Speed. Prête pour le jeu 4K 120 FPS.',
    price_pi: 45.0,
    image_url: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80',
    ],
    category: 'Jeux',
    status: 'active',
    stock: 5,
    views_count: 410,
    is_demo: true,
    created_at: new Date(Date.now() - 3600000 * 60).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      username: 'GameVault_Pi',
      is_seller: true,
    },
  },
  {
    id: 'demo-prod-07',
    seller_id: 'demo-seller-watch',
    title: 'Montre Connectée Smartwatch AMOLED & Suivi Santé GPS',
    description: 'Écran AMOLED toujours allumé, autonomie jusqu\'à 14 jours, étanche 5 ATM, capteurs cardio et SpO2 précis.',
    price_pi: 9.8,
    image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    ],
    category: 'Accessoires',
    status: 'active',
    stock: 15,
    views_count: 175,
    is_demo: true,
    created_at: new Date(Date.now() - 3600000 * 72).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      username: 'SmartGearLab',
      is_seller: true,
    },
  },
  {
    id: 'demo-prod-08',
    seller_id: 'demo-seller-home',
    title: 'Machine à Café Espresso Automatique Broyeur à Grains',
    description: 'Savourez un espresso parfait moulu à la minute. Pression 19 bars, buse vapeur inox pour cappuccinos onctueux.',
    price_pi: 29.5,
    image_url: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&auto=format&fit=crop&q=80',
    ],
    category: 'Maison',
    status: 'active',
    stock: 6,
    views_count: 98,
    is_demo: true,
    created_at: new Date(Date.now() - 3600000 * 96).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      username: 'HomeBarista',
      is_seller: true,
    },
  },
  {
    id: 'demo-prod-09',
    seller_id: 'demo-seller-dev',
    title: 'Pack Audit de Sécurité & Développement d\'Application Pi Network',
    description: 'Prestation de conseil et intégration complète du Pi SDK v2.0 pour votre projet Web3. Audit smart contracts et bonnes pratiques de sécurité backend.',
    price_pi: 60.0,
    image_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80',
    ],
    category: 'Services',
    status: 'active',
    stock: 10,
    views_count: 320,
    is_demo: true,
    created_at: new Date(Date.now() - 3600000 * 120).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      username: 'WalboyDevStudio',
      is_seller: true,
    },
  },
  {
    id: 'demo-prod-10',
    seller_id: 'demo-seller-beauty',
    title: 'Coffret Soins Bio Sérum Acide Hyaluronique & Huile Précieuse',
    description: 'Formule 100% naturelle certifiée biologique. Hydratation intense, anti-âge naturel fabriqué en France.',
    price_pi: 5.5,
    image_url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=80',
    ],
    category: 'Beauté',
    status: 'active',
    stock: 20,
    views_count: 85,
    is_demo: true,
    created_at: new Date(Date.now() - 3600000 * 150).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      username: 'NaturaBeauty',
      is_seller: true,
    },
  },
  {
    id: 'demo-prod-11',
    seller_id: 'demo-seller-food',
    title: 'Coffret Dégustation Chocolats Fins Grands Crus Bio',
    description: 'Sélection artisanale de fèves de cacao rares d\'Amérique du Sud et de Madagascar. 24 pièces d\'exception.',
    price_pi: 3.8,
    image_url: 'https://images.unsplash.com/photo-1548907040-4baa42d10919?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1548907040-4baa42d10919?w=800&auto=format&fit=crop&q=80',
    ],
    category: 'Alimentation',
    status: 'active',
    stock: 30,
    views_count: 110,
    is_demo: true,
    created_at: new Date(Date.now() - 3600000 * 180).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      username: 'ChocoGourmet',
      is_seller: true,
    },
  },
  {
    id: 'demo-prod-12',
    seller_id: 'demo-seller-gear',
    title: 'Sac à Dos Étanche Urbain Anti-Vol avec Port USB Intégré',
    description: 'Compartiment renforcé pour ordinateur 16 pouces. Tissu déperlant haute densité et poches secrètes RFID.',
    price_pi: 6.4,
    image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
    ],
    category: 'Autres',
    status: 'active',
    stock: 14,
    views_count: 130,
    is_demo: true,
    created_at: new Date(Date.now() - 3600000 * 200).toISOString(),
    updated_at: new Date().toISOString(),
    seller: {
      username: 'TravelPackGear',
      is_seller: true,
    },
  },
];
